# -*- coding: utf-8 -*-
from Test_function import FunctionGetdata
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QGridLayout, QWidget, QTableWidget, QTableWidgetItem
from PyQt5.QtCore import QSize, Qt

# Form implementation generated from reading ui file '.\Front\Design_Ui\Form_to_diplom_var1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from molibden6.diplom2 import measure

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.setMinimumSize(QtCore.QSize(886, 704))
        Dialog.setMaximumSize(QtCore.QSize(886, 704))
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(270, 599, 321, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.pushButton_StartGetTime = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_StartGetTime.setObjectName("pushButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButton_StartGetTime)
        self.pushButton_StopGetTime = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_StopGetTime.setObjectName("pushButton_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton_StopGetTime)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(50, 20, 801, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(380)
        self.tableWidget_2 = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_2.setGeometry(QtCore.QRect(50, 300, 381, 271))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(170)
        self.tableWidget_4 = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_4.setGeometry(QtCore.QRect(470, 300, 381, 271))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(2)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        self.tableWidget_4.horizontalHeader().setDefaultSectionSize(170)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_StartGetTime.setText(_translate("Dialog", "Старт"))
        self.pushButton_StopGetTime.setText(_translate("Dialog", "Стоп"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Название параметра"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Значение"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Название параметра"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Значение"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Название параметра"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Значение"))


class MainWindowsToDiplom(QtWidgets.QWidget, Ui_Dialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

        self.pushButton_StartGetTime.clicked.connect(self.start)
        self.pushButton_StopGetTime.clicked.connect(self.stop)
        self.FunctionGetdata = FunctionGetdata()
        self.FunctionGetdata.dataChanged.connect(self.dataThreads)
        self.FunctionGetdata.finished.connect(self.finishThreads)
        self.FunctionGetdata.working = False
        self.tableWidget.setRowCount(3)

    def start(self):
        self.FunctionGetdata.working = True
        self.FunctionGetdata.start()

    def stop(self):
        self.FunctionGetdata.working = False
        self.FunctionGetdata.stoped()

    def dataThreads(self, text):
        for number_names in range(len(self.FunctionGetdata.names_rows)):
            print(text)
            self.tableWidget.setItem(number_names, 0, QTableWidgetItem(self.FunctionGetdata.names_rows[number_names]))
            self.tableWidget.setItem(number_names, 1, QTableWidgetItem(str(text['med'][0])))
            self.tableWidget.setItem(number_names, 1, QTableWidgetItem(str(text['speed'][0])))
            self.tableWidget.setItem(number_names, 1, QTableWidgetItem(str(text['speed_2'][0])))

    def finishThreads(self, text):
        self.tableWidget.setItem(0,0, QTableWidgetItem(text))

